//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerHost.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.ICentralBankService")]
    public interface ICentralBankService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentralBankService/ConvertValue", ReplyAction="http://tempuri.org/ICentralBankService/ConvertValueResponse")]
        DomainService.Objects.ConverterObject ConvertValue(double value, string currencyValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentralBankService/ConvertValue", ReplyAction="http://tempuri.org/ICentralBankService/ConvertValueResponse")]
        System.Threading.Tasks.Task<DomainService.Objects.ConverterObject> ConvertValueAsync(double value, string currencyValue);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICentralBankServiceChannel : ServerHost.ServiceReference2.ICentralBankService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CentralBankServiceClient : System.ServiceModel.ClientBase<ServerHost.ServiceReference2.ICentralBankService>, ServerHost.ServiceReference2.ICentralBankService {
        
        public CentralBankServiceClient() {
        }
        
        public CentralBankServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CentralBankServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CentralBankServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CentralBankServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DomainService.Objects.ConverterObject ConvertValue(double value, string currencyValue) {
            return base.Channel.ConvertValue(value, currencyValue);
        }
        
        public System.Threading.Tasks.Task<DomainService.Objects.ConverterObject> ConvertValueAsync(double value, string currencyValue) {
            return base.Channel.ConvertValueAsync(value, currencyValue);
        }
    }
}
