//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainService.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class store_positions
    {
        public int Id { get; set; }
        public string positionName { get; set; }
        public int positionType { get; set; }
        public float positionValue { get; set; }
        public float positionPrice { get; set; }
        public string positionCurrency { get; set; }
        public float priceCurrency { get; set; }
    }
}
